"""conversations, messages, delegate threads

Conductor's initial schema (Phase 3 slice 4): master-conversation persistence —
``conversations`` (soft-deletable via ``deleted_at``) and immutable
``conversation_messages`` children storing the loop outcome denormalized
(``tool_calls`` JSON + ``stop_reason``), same shape as PCC's — plus
``delegate_threads``, the DB-backed ThreadStore mapping
``(master_conversation_id, app_name)`` to the app's subagent thread so
follow-ups keep carrying context app-side across restarts.

Revision ID: cee4b4f848c9
Revises:
Create Date: 2026-07-12

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "cee4b4f848c9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "delegate_threads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("master_conversation_id", sa.String(), nullable=False),
        sa.Column("app_name", sa.String(), nullable=False),
        sa.Column("subagent_conversation_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("master_conversation_id", "app_name"),
    )
    with op.batch_alter_table("delegate_threads", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_delegate_threads_master_conversation_id"),
            ["master_conversation_id"],
            unique=False,
        )

    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("user", "assistant", name="conversationrole"), nullable=False),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("tool_calls", sa.JSON(), nullable=True),
        sa.Column("stop_reason", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_messages_conversation_id"),
            ["conversation_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_messages_conversation_id"))

    op.drop_table("conversation_messages")
    with op.batch_alter_table("delegate_threads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_delegate_threads_master_conversation_id"))

    op.drop_table("delegate_threads")
    op.drop_table("conversations")
    # ### end Alembic commands ###
